### ISSUE TITLE
code execute error

### ISSUE THREAD

**Issue by bert13069598** [fatalfeel/DeblurGAN#2]
![image](https://user-images.githubusercontent.com/89738612/204434261-7dd15c8b-9b41-4f47-a5a6-4fc104a69b28.png)

python3 ./test.py --dataroot ./data/blurred --model test --dataset_mode single --cuda True

The above error occurred while executing the code. For the pth model file, I used the file that I turned 2000 times below. Does anyone have the same problem???

**Comment by fatalfeel** [comment]
most cuda problem is pytorch version
